### PR TITLE
Added a TypeScript definitions file to the docs

### PR DESCRIPTION
**Pull request by tel**
See #101.

The goal of this file is to aid interop with teams using Deku with TypeScript while also providing documentation value to Deku itself.

### Todo

* [x] Write a sample component and app demonstrating the use of the `d.ts` file.
* [x] Determine a better way to write component modules which benefits from type inference properly.

### CODE REVIEW

**Comment by tel** [comment]
Here's a pretty silly example usage

```typescript
/// <reference path="typings/deku/deku.d.ts" />

import Deku = require('deku');
var e = Deku.element;

// Component-as-module 
module Counter {
  
  var e = Deku.element;
  
  export interface P {
    count: number;
  }
  
  export interface S {}
  
  export function render(component: Deku.Component<P, S>, setState: (state: S) => void): Deku.VirtualNode<P, {}> {
    return e('div', {}, [component.props.count.toString()]);
  }
  
}

// Initialize tree
var tree = Deku.tree(Deku.element(Counter, {}));

window.onload = (ev) => {
  var root = document.getElementById("root");
  var n = 1;
  
  // Event loop
  function loop(): void {
    n += 1;
    tree.mount(Deku.element(Counter, { count: n }));    
    setTimeout(loop, 1000);
  }
  
  // Mount the tree and start the loop
  Deku.render(tree, root);
  loop();
}
```

**Comment by tel** [comment]
[Here's a MUCH more complete version of this example.](https://github.com/tel/typescript-deku-rx-test)

**Comment by tel** [comment]
Working this example has driven a few improvements to the definitions file. I think one thing remaining I'd like to test are ways to get module types driven. Right now writing Components requires copying and pasting the types in more or less.

**Comment by tel** [comment]
The new style for definition [`Counter`](https://github.com/tel/typescript-deku-rx-test/blob/master/components/counter.ts) gets far better inference.

**Comment by anthonyshort** [comment]
Nice work! I think it's fine if the spec object has explicitly built, it's really just an implementation detail. I don't use typescript so I'll have to take your word for it if you think it's ready to merge :)

**Comment by tel** [comment]
I think it's functional now. There are surely rough edges to round off still, but feel free to merge.

**Pull request merged**
