### PR TITLE
API v0.1.0

### PR DESCRIPTION
**Pull request by anthonyshort**
Looking at the API it seems like it's setup to eventually allow multiple mounted elements. With the layers we found out that we'd only have a single mounted component, but it could render to multiple elements instead. So I had this idea for the API:

```js
var app = deku()
app.use(someDataSource)
app.use(router)

// Mount the component on the app. We’re using virtual nodes
// so there is no concept of props anymore. The router would mount
// different components on different routes at the top-level
app.mount(
  <MyComponent foo="bar">
    <div>Hello World</div>
  </MyComponent>
)

// Render the app to the DOM. Provide additional layers if
// they’re needed by components. If there isn’t a component mounted,
// it just waits until one is mounted.
var dom = render(app, el);

// You have access to tools for testing and debugging
// dom.entities
// dom.pools
// dom.handlers
// dom.update()
// dom.remove()

// Render string.
var str = renderString(app);

// Maybe some future, external renderers
var canvas = renderCanvas(app, el);

// Updating is just a matter of mounting another component. It can also mount
// any type of virtual element, not just components.
app.mount(
  <div onClick={fn}>
    <MyComponent foo="baz" />
  </div>
)

// Or you can unmount the component from the app and the DOM will
// remove the element from the container.
app.unmount()
```

The big difference is that we can remove the whole concept of `setProps` if we look at it as just mounting a virtual node onto the app. The renderers (`render` and `renderString`) just render the app with all of it's data and the mounted virtual node.

I've decided to keep the `entities`, `pools`, and `handlers` objects off the app so they don't mutate it and instead just return a `rendered` object that has these on them. This is only really used in debugging, a real app would looks like this:

```js
var app = deku()
app.use(someDataSource)
app.use(router)
render(app, el);
``` 

When we add layers, the `render` function can just take an optional object as it's second param:

```js
render(app, {
  main: el,
  overlay: overlayEl
})
```

If we wanted to, we could add some API sugar for the two main renders:

```js
var dom = app.render(el)
var str = app.renderString()
```

Which could add the extra benefit of only allowing the app to be rendered to the DOM once. Or we could make all of the renderers plugins, so it's up to the user to decide how it's rendered:

```
var app = deku()
app.use(render(el, { immediate: true }))
app.mount(<MyComponent />)
var dom = app.render()

var app = deku()
app.use(renderString())
app.mount(<MyComponent />)
var str = app.render()

var app = deku()
app.use(renderCanvas())
app.mount(<MyComponent />)
var canvas = app.render()
```

My main gripe about having `.render` and `.renderString` on the app is that it means all renderers (including future renderers) don't have the same API. I think however we decide the API will look, using all renderers should look the same.

### CODE REVIEW

**Comment by lancejpollard** [comment]
Awesome it will be nice to finalize this :)

Yeah this is really nice (since we only need 1 top-level component, since layers solve that).

```js
app.mount(
  <div onClick={fn}>
    <MyComponent foo="baz" />
  </div>
)
app.unmount()
```

It's cool there's no setProps either since it's not necessary. However, having `app.update` or something along those lines (liking that verb for changing things) would be super helpful for debugging. You know in your mind which components are reading from which data sources (since it's in the component definition), and so could just `app.update(<source>, <data>)` and follow the update chain, or see if something isn't updating or whatever.

> I've decided to keep the entities, pools, and handlers objects off the app so they don't mutate it and instead just return a rendered object that has these on them.

Wondering what is the issue with mutating it? In terms of [to-fast-properties](https://github.com/sindresorhus/to-fast-properties), chucking these things onto the app won't cause any performance issues. That would only be a problem more for big lists of objects, or where you're accessing many values every frame.

Having it be on the app would have a few benefits over having it on the renderer, mostly:

- Only have to many one object instead of two at the top level.
- Seems simpler to get setup for a newcomer having only 1 thing to import there.
- It would be simpler to debug. For example, say you have a breakpoint in the data store, or somewhere outside the renderer. You'd have no access to the renderer, or you'd have to drill out pretty far to get there. But if it was on the app you could just take a look real quick. Seems like it would simplify debugging workflow a bit.

While putting these objects on the renderer is more technically pure, it feels sorta like positioning a button label in the exact center because it's technically correct, when our eyes actually prefer it slightly off center :)

```js
var app = deku()
app.use(render(el, { immediate: true }))
app.mount(<MyComponent />)
```

Liking that.

> My main gripe about having .render and .renderString on the app is that it means all renderers (including future renderers) don't have the same API.

Yeah I feel you there. The main thing though is, from "userland", they only care about defining components and their templates. Maybe wiring up some data. They don't care really how it renders, just that it renders, wouldn't you say?

So it's like, question then. Should we change the userland API to support something they shouldn't have to worry about? That's where it starts to feel off for me.

My gut's saying that it only needs "renderer", which supports all of what the DOM does (basic html, svg, canvas, webgl). That thing takes the virtual nodes, and then figures out which "engine" to use or whatever. But all that is transparent to the user. So it seems like it shouldn't even really show up in the userland api.

Way down the road, it's possible there is a new rendering method that everyone wants, but then we can figure it out then. Even then we could figure out how to make it transparent.

For stringifying, this seems like a very different case than rendering. The main difference is that `renderString` is stateless, while the real rendering is super stateful and complicated. So to make those two api's the same is what's causing your gripe; they're really not related at all, other than they both act on the virtual nodes in some way.

Conceptually, it feels separated/clearer if you have the real "rendering", and then you can do `app.toString()` or `app.renderString()` or `app.toHTML()`.

I dunno, my 2c. Seems like there is a way to prevent the string stuff from affecting the typical user's api.

Does that make any sense? Sorry that turned out to be way longer than I thought haha.

**Comment by anthonyshort** [comment]
:+1: to putting them on the app then if that makes life easier for debugging.

For the fast properties, I made sure all the objects we're iterating over inside the `render` function never call delete. That should make looping through the entities really quick.

> They don't care really how it renders, just that it renders, wouldn't you say?

I actually think you do care how it renders. Components might not necessarily work in every render type, it would mean that components themselves need to say what type of renderer they need. It also means we'd need to package every type of renderer with deku, some of which people won't care about.

I'd still say the `renderString` function is at least tied to the DOM renderer, since that renders HTML. Some other string renderer, say for canvas, might render the app as an image. If we add the render "plugin" by default then the `app` will have the `render` and `renderString` functions on it by default. Then the user doesn't have to worry about it at all (for now).

I was sort of thinking it would look like this:

```js
import {App,render} from 'deku';

var app = App(<MyComponent />)
app.use(render(el, { immediate: true }))
app.render()
```

Having to specify a renderer isn't that bad, since they need to anyway. They might want to render a tree of components in a few different ways. But something like this could work

```js
var app = deku(<MyComponent />)
app.render(el, { immediate: true }))
```

That will work for now. If we ever get a bunch of different renderers we could package them up separately.

**Comment by lancejpollard** [comment]
Boom that looks hardcore!

```js
var app = deku(<MyComponent />)
app.render(el, { immediate: true }))
```

**Comment by anthonyshort** [comment]
```js
var app = deku()

// Mount a virtual node onto the app. This can be called multiple times and 
// any active renderers can swap their current representation for a new one. Emits a 
// `mount` event.
app.mount(<MyComponent />)

// Render the current mounted element to the DOM. If there isn't a mounted element
// this should probably throw an error. Returns an object with functions to instantly update the
// DOM renderer or to destroy it.
var dom = app.render(el, options)
dom.update()
dom.remove()

// Remove the mounted element. Any active renderers will destroy their current representation.
// Emits an `unmount` event.
app.unmount()

// Render the current mounted element to a string. Returns an object with a string
// for each layer that has been rendered to. 
var {one, two} = app.renderString(options)

// Add a new data source. Emits a `subscribe` event.
app.source('name', fn)

// Update a data source. It should throw if the source hasn't been defined yet.
app.update('name', data)

// Use a plugin
app.use(fn)

// Removes all source subscriptions
app.unsubscribe()
```

Only difference is that I think we need a `mount` function so that you can change the properties at the top level. Other than that, I think it's a winner :)

**Comment by lancejpollard** [comment]
LGTM! What about layers?

**Comment by anthonyshort** [comment]
We could just pass in an object in `render`

```js
app.render({
  layers: {
    main: el
  },
  options: {
    renderImmediate: true
  }
})
```

**Comment by lancejpollard** [comment]
That works. Is the thinking behind not doing..

```js
var app = deku()
  .source('resource', resource)
  .source('articles', articles)
  .layer('main', el)
  .layer('overlay', overlay)
  .layer('dialog', dialog)
  .layer('notification', notification);
```

because the layers are assoc with the renderer?

**Comment by anthonyshort** [comment]
yeah pretty much. Anything related to it should be in that function I think. If we want to keep the renderer included with the app for simplicity I think we need to decide a couple of things:

1. Can we call render multiple times using different options? Would this mount to a separate element and also stay in sync? Or can there only be one rendered version at a time? 
2. What the best way to remove the rendered element from the DOM? 
3. What happens when you call a render method when there is no mounted virtual element?

**Comment by lancejpollard** [comment]
kk. It's up to you how you think it should work. For me the easiest way to think about it is the rendering happens automatically, I just need to give it the root component. So just

```js
app.mount(<MyComponent />)
```

That renders, and since it has the layer info already, it knows how to render it. Doesn't seem like you'd need to call render manually. Seems like that would answer all 3 questions?

1. You never call render manually. Though, it would be very nice, for testing and debugging, to be able to dynamically change the rendering options to do sync vs. async. That's how it was temporarily working now with `world.options.immediate`. You can just change that in the debugger and the renderer would use that. Or `dom.options.immediate` or however.
2. Calling `app.unmount()` would clear the stuff appended to all layers.
3. By just doing `app.mount(<MyComponent />)` + layers we can avoid it.

**Pull request merged**
