### PR TITLE
Add DOM pooling

### PR DESCRIPTION
**Pull request by anthonyshort**
Adds DOM pooling using [dom-pool](https://github.com/ChrisAntaki/dom-pool). This allows us to re-use elements instead of trashing them and creating new ones. This should speed things up a lot.

Need to do some more testing with this to make sure it's working correctly.

### CODE REVIEW

**Comment by anthonyshort** [comment]
@lancejpollard Could you have a quick look over this and see if there's anything that stands out?

This also adds a `set` method to Components to allow setting arbitrary options. The renderers can use these options to turn on/off features. You can disable the pooling like this:

```js
var Button = component()
  .set('disablePooling', true)
```

Should we even allow this? Forcing people to not store DOM elements could be good practice anyway. If it's not something we need I can remove all the option code.

**Comment by anthonyshort** [comment]
@ChrisAntaki Does this use of dom-pool look right to you? I'm having to manually remove all the attributes and child nodes from an element after I pull it from the storage. It might be nice if the pooling object handled all this for me. Then you could just through it a DOM node then all child nodes would also be added to the pool.

**Comment by ChrisAntaki** [comment]
@anthonyshort The usage looks great. You could potentially speed up the first render by waiting to clean DOM nodes until they are about to be returned :watch:. Thanks for your ideas!

**Comment by ChrisAntaki** [comment]
@scottcorgan Glad you like it!

**Pull request merged**
